#yaml input file

#Dataset Path
dataset_folder: dataset

#How many frames to load simultaneously
buffer_stream_dim_ts: 21
buffer_stream_dim_tr: 21
subsampling: 'no'

#Output model prefix name
model_name: 'model_log'
restart:  'no' 


#Net parmater
dimension_encoder_2body: 5
dimension_encoder_3body: 5
number_of_decoding_layers: 2
number_of_decoding_nodes: 25 25
number_of_epochs: 20000

batch_size: 4
activation_function: tanh
alpha_bound: 5.


loss_energy_prefactor: 0.1
loss_force_prefactor: 1.


#expdec initial_learningrate final_learningrate decay_steps
#cosann initial_learningrate first_decaystep t_mul m_mul alpha
lr_dense_net: cosann 0.01 2.5 1.4 0.9 0.00000001
lr_phys_net:  cosann 0.01 2.5 1.4 0.9 0.00000001
optimizer_net: adam
optimizer_phys: adam
loss_method: huber

Seed: 30
